name: Pipeline de Testes Cypress

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  testes-cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Instalar Dependências
        run: npm install

      - name: Rodar Testes Cypress
        run: npm run allure:run
        # Continua mesmo se os testes falharem, para podermos gerar o relatório do erro
        continue-on-error: true

      # PASSO NOVO: Baixa o histórico de relatórios da branch gh-pages
      - name: Baixar Histórico do Relatório
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Gerar Relatório Allure com Histórico
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          gh_pages: gh-pages

      - name: Deploy do Relatório para GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # A pasta que contém o relatório e o histórico
          publish_dir: allure-history
          # Garante que a branch correta seja usada
          publish_branch: gh-pages
